export const pendingProjects = [
    {
        title: 'El día que Maradona regresó al Azteca / DISNEY+',
        src: '/mainVideos/maradona.mp4',
        poster: '/posters/maradona.webp',
        linkVideoLargo: '/videos/maradona-trailer.mp4',
        Label: 'ESPN+ / DISNEY+',
        credits: [
            { title: 'Client', value: 'ESPN+ / DISNEY+' },
            { title: 'Production Company', value: 'ESPN ORIGINALS / MONKEY LABEL FILMS' },
            { title: 'Director', value: 'MARTIN FRADKIN' },
            { title: 'Producer', value: 'VILMA OBANDO / DANIELA MARTINEZ NANNINI / MARTIN LAPPISONDE / JUAN IRIGOYEN' },
            { title: 'Producer Director', value: 'FAUSTO CEBALLOS' },
            { title: 'DOP', value: 'JOAQUIN NEIRA / GERALD LEE / JUAN IRIGOYEN' },
            { title: 'Sound', value: 'CARLOS MARCELLAN' },
            { title: 'Post Production', value: 'MONKEY LABEL FILMS' },
            { title: 'Edit', value: 'DANIELA BENEDETTI' },
            { title: 'Assistant Editor', value: 'SANTIAGO BURGOS' },
            { title: 'Deliveries', value: 'GABRIELA CASTRO MARTINEZ' },
            { title: 'Colourist', value: 'JUAN CELESTINO' },
            { title: 'Sound Design', value: 'PAFUNDI / QUINTANA' },
            { title: 'Equipment', value: 'KATPA RENTALS / ANGULAR RENTALS' },
            { title: 'Set Design', value: 'MELON MANGA' },
            { title: 'Set Production Staff', value: 'PAULA RIVAS / CECILIA CORRENTI / CARLOS MARCELLAN' },
            { title: 'Graphic Design', value: 'MARIANO MORONI' },
        ],
    },
    {
        title: 'Último Tren a Norteamérica / DISNEY+',
        src: '/mainVideos/ultimo-tren-norteamerica.mp4',
        poster: '/posters/ultimo-tren-norteamerica.webp',
        linkVideoLargo: '/videos/ultimo-tren-norteamerica-trailer.mp4',
        Label: 'ESPN+ / DISNEY+',
        credits: [
            { title: 'Client', value: 'ESPN+ / DISNEY+' },
            { title: 'Production Company', value: 'ESPN ORIGINALS / MONKEY LABEL FILMS' },
            { title: 'Director', value: 'MARTIN FRADKIN' },
            { title: 'Producer', value: 'VILMA OBANDO / DANIELA MARTINEZ NANNINI / JUAN IRIGOYEN' },
            { title: 'Producer Director', value: 'FAUSTO CEBALLOS' },
            { title: 'DOP', value: 'CONRADO TAINA / GERALD LEE / JUAN IRIGOYEN' },
            { title: 'Sound', value: 'CARLOS MARCELLAN' },
            { title: 'Post Production', value: 'MONKEY LABEL FILMS' },
            { title: 'Edit', value: 'DANIELA BENEDETTI / ARIEL LEPE' },
            { title: 'Assistant Editor', value: 'SANTIAGO BURGOS / BELEN RISSO PATRON' },
            { title: 'Deliveries', value: 'GABRIELA CASTRO MARTINEZ' },
            { title: 'Colourist', value: 'CLARA BIANCHI' },
            { title: 'Sound Design', value: 'PAFUNDI / QUINTANA' },
            { title: 'Equipment', value: 'KATPA RENTALS' },
            { title: 'Graphic Design', value: 'MARIANO MORONI' },
        ],
    },
].map(({ title, credits, src = '', poster = '', linkVideoLargo = '', Label = '' }) => ({
    index: -1,
    src,
    poster,
    btnText: title,
    Titulo: title,
    Label,
    linkVideoLargo,
    linkcorto: src,
    credits,
}));
